### PR TITLE
Unify integration API 

### LINKED ISSUE #974: Unify integration API
There is

* [`fn askama_warp::reply(&impl Template) -> Response`](https://github.com/djc/askama/blob/178a6895d47a397e8d6bffcbc34c9782b08b0b8c/askama_warp/src/lib.rs)
* [`fn askama_tide::try_into_body(&impl Template) -> Result<Body>`](https://github.com/djc/askama/blob/178a6895d47a397e8d6bffcbc34c9782b08b0b8c/askama_tide/src/lib.rs)
* [`fn askama_tide::into_response(&impl Template) -> Response`](https://github.com/djc/askama/blob/178a6895d47a397e8d6bffcbc34c9782b08b0b8c/askama_tide/src/lib.rs)
* [`fn askama_rocket::respond(&impl Template) -> Result<_>`](https://github.com/djc/askama/blob/178a6895d47a397e8d6bffcbc34c9782b08b0b8c/askama_rocket/src/lib.rs)
* [`fn askama_axum::into_response(&impl Template) -> Response`](https://github.com/djc/askama/blob/178a6895d47a397e8d6bffcbc34c9782b08b0b8c/askama_axum/src/lib.rs)
* [`<T as TemplateToResponse>::to_response(&self) -> Response`](https://github.com/djc/askama/blob/178a6895d47a397e8d6bffcbc34c9782b08b0b8c/askama_actix/src/lib.rs)

Shouldn't we use the moment, if we upload new versions of the integration crates anyway, to unify the APIs amongst the crates?

I like the API of `askama_tide` the best: One function `try_into_response(&impl Template)` to generate a `Result<_>`, and one function `into_response(&impl Template)` to generate a response that might be an error page.

### PR DESCRIPTION
**Pull request by Kijewski**
Resolves #974.

### CODE REVIEW

**Comment by Kijewski** [comment]
Now every integration crate exports `askama::*`, the framework crate, `try_into_response()` and `into_response()`.

**Comment by Kijewski** [comment]
> I'd prefer to standardize on using `&impl askama::Template + ?Sized`.

The `try_into_response()` functions all depend on `T` for `T::MIME_TYPE`. I wanted both functions to look the same, both using explicit generics, because the implicit variant cannot be used for `try_into_response()`. Should I change `into_response()` anyway?

**Comment by djc** [comment]
> > I'd prefer to standardize on using `&impl askama::Template + ?Sized`.
> 
> The `try_into_response()` functions all depend on `T` for `T::MIME_TYPE`. I wanted both functions to look the same, both using explicit generics, because the implicit variant cannot be used for `try_into_response()`. Should I change `into_response()` anyway?

Ah, that's fair. Let's leave it then.

Would you mind squashing the reordering into the originating commits?

**Comment by Kijewski** [comment]
Squashed.

**Review by djc — APPROVED** [review]

**Pull request merged**
