### PR TITLE
WIP: make askama_rocket and askama_derive ready for rocket 0.5

### PR DESCRIPTION
**Pull request by flo-l**
I tried it locally, seems to work for me. But I'm not sure if I got the lifetimes right..

Anyhow, this PR should only be merged after Rocket releases 0.5.

Thank you for askama, I like it a lot :)

### CODE REVIEW

**Comment by djc** [comment]
Can you use a git dependency on Rocket here, so we can actually test this in CI?

**Comment by shritesh** [comment]
FWIW, I've pointed Rocket to git and updated the test to use the new API at https://github.com/shritesh/askama/commit/b9f7a58cee2be9beb52449bedab06ee685287b06. 
Thank you for the PR.

**Comment by LEXUGE** [comment]
As a remainder, the rocket has recently released 0.5 rc release, it might be a good point to update `askama_rocket` as well.

**Comment by djc** [comment]
If someone is more invested than this PR's author, maybe just start a new PR?

**Comment by djc** [comment]
This was pulled into #495, closing.

**Pull request closed without merging**
