### PR TITLE
Add regression tests for `if let` code generation

### LINKED ISSUE #1038: Add tests for generated code
In https://github.com/djc/askama/pull/1037, I tried to add tests for generated content but it was quite ugly so I finally didn't put it into the PR until I find a better implementation.

I still think that we should have AST tests, in particular to ensure that code generation improvements don't have "hidden" regressions and that changes don't go unnoticed.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Follow-up of https://github.com/djc/askama/pull/1037.
Fixes #1038.

Thanks to @Kijewski, I was able to simplify the test code quite a lot. :)

### CODE REVIEW

**Comment by Kijewski** [comment]
Maybe we can put even more responsibility into syn's hands? https://github.com/djc/askama/commit/cfbd804351e58ba68bbed977fcf2dd2445fd1ec1

**Comment by GuillaumeGomez** [comment]
Fine by me. 👍 Don't hesitate to push on my branch.

**Review by djc — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
Applied suggestions.

**Review by Kijewski — APPROVED** [review]
:+1:

**Pull request merged**
