### PR TITLE
upgrade dependencies(actix-web 0.7 -> 2, bytes 0.4 -> 0.5)

### LINKED ISSUE #246: Support actix-web v1.0
The `feature = ["with-actix-web"]` functionality currently depends on actix-web v0.7.0, and won't work with v1.0.

I tried updating the dependency locally, and it looks like the interface of actix-web's `Responder` trait changed in 1.0. ([v1.0] vs. [v0.7])

[v1.0]: https://docs.rs/actix-web/1.0.0/actix_web/trait.Responder.html
[v0.7]: https://docs.rs/actix-web/0.7.19/actix_web/trait.Responder.html

### PR DESCRIPTION
**Pull request by DCjanus**
Close #246

### CODE REVIEW

**Comment by DCjanus** [comment]
I've tried to upgrade `gotham`, met a lot of problem, looks like gotham is no longer in active maintenance phase. Maybe we should remove `gotham` support?

**Comment by djc** [comment]
Awesome, thanks!

**Comment by djc** [comment]
I think the split cannot work or is quite tricky. I'd like to get the upgrade in anyway!

**Comment by DCjanus** [comment]
You are right, I've tried and found I don't know how to resolve that. Reopen this.

**Comment by DCjanus** [comment]
BTW, maybe we should remove `gotham` support, looks like it is no longer in active maintenance.

**Comment by djc** [comment]
As for Gotham, looks like their latest commit to master was 10 days ago - that hardly seems dead to me.

**Pull request merged**
