### PR TITLE
Fix nested and imported macro support

### PR DESCRIPTION
**Pull request by botika**
Description in the tests files

### CODE REVIEW

**Comment by djc** [comment]
I've rebased them into 16b577e3070ca935180652e7ce24563bd396babc and f29c12f469ccb76ed06aff6d6dc037dfd7dd2406 and reworded the commit messages a little bit -- but the patches themselves are basically as I would've done them. Thanks a lot!

Would it help you if I release a 0.7.2 release with this?

**Comment by botika** [comment]
It is not yet in production and I am with the git. If I can help you, tell me what I can help. Thank you

**Comment by botika** [comment]
I'm starting a new business webapp and I'm going to use Askama  for a real server side that I call jsxinja with the help of babel and a simple transpiler.

**Comment by djc** [comment]
Sounds cool!

**Pull request closed without merging**
