### PR TITLE
Fix invalid `if let` code generation

### LINKED ISSUE #1033: if let chain has a weird behaviour
I expected this code:

```jinja
{%- if let Some(query) = search_query && !query.is_empty() %}
```

To either emit an error about the `&&` after `if let Some` or to work, instead it generated:

```rust
if let Some(query,) = &(search_query && !self.query.is_empty()) {
```

Which is a very unexpected in-between.

I think it should generate `if let Some(query) = search_query && !self.query.is_empty()`. What do you think?

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #1033.

We cannot test the generated code since the if-let chain feature is still unstable. So I thought about two possibilities to still test this:
 * Testing the generated code.
 * Adding a new "nightly" feature for these tests and add a nightly check in the CI.

Here are the cases to be checked:

```jinja
{% if let Some(query) = s && !query.is_empty() %}{{query}}{% endif %}

{% if let Some(s) = s && !s.is_empty() %}{{s}}{% endif %}

{% if let Some(s) = s %}{{ s }}{% endif %}
```

Where `s` is `Option<String>`.

### CODE REVIEW

**Review by Kijewski — APPROVED** [review]

**Comment by djc** [comment]
Maybe the generator should desugar let chains into something that works on stable? It's okay if the generated code isn't the prettiest.

**Comment by GuillaumeGomez** [comment]
I don't think we should implement our own condition lexer, we should just rely on the rust compiler to handle this part for us. For example, it becomes particularly tricky in cases like:

```rust
if let Some(x) = y || z == "x" && whatever
```

It requires to generate `else if z == "x"` and in both `if` branches to have also `whatever`.

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/djc/askama/issues/1038 about this.

**Comment by djc** [comment]
(Would prefer if you don't merge non-trivial PRs without my approval.)

**Pull request merged**
