### PR TITLE
Add specialization

### PR DESCRIPTION
**Pull request by botika**
Nightly
```
Big table               time:   [280.96 us 281.06 us 281.20 us]
                        change: [-56.768% -56.745% -56.721%] (p = 0.00 < 0.05)

Teams                   time:   [485.02 ns 486.16 ns 487.31 ns]
                        change: [-43.564% -43.426% -43.294%] (p = 0.00 < 0.05)
```

### CODE REVIEW

**Comment by botika** [comment]
At stable, the average escape time has been improved, remove the false positives, ascii 34 to 62, by means of a static table, it does not use simd. 

At nightly, simd has been integrated along with specialization, reduction of false positives to 1/64, full coverage and optimizations.

**Comment by djc** [comment]
So that's a big improvement on nightly, but it looks like the improvement comes largely from specialization (more so than from the SIMD implementations). I'm still unconvinced about the benefits of SIMD by itself, and also not sure about the complexity here.

Here's some alternative thinking: what if we can make turn `MarkupDisplay` into a trait such that escaping is more pluggable? We should solve #108 and #136 at the same time as allowing you to plug in your custom escaping code.

**Comment by botika** [comment]
I agree, the best improvement in this e2e is offered by the specialization. 

The complexity is high but the performance is 10% below memchr3. It also has a relative coverage of 100% and only works at nightly. In stable it works by static table with what gives better performance for 2 or more false positives than the previous one.

 What do you propose for SIMD? for the results of other implementations, it will not have much better performance. We leave it or what else can I do?

As for the trait, we can be done but we can only implement it on primitive types (usize, i8, str, String, ..), so it will stop working in other structures that imp Display. That or I do not just understand you.

As for the #108 and #136, I do not understand it very well, I had thought about the specialization for these. You can explain a little more about this solution for the this issues.

**Comment by botika** [comment]
I enclose the [benchmarks](https://github.com/rust-iendo/v_htmlescape/tree/master/benches#benches) with throughput , they are the same data that [rust-memchr](https://github.com/BurntSushi/rust-memchr/tree/master/bench/data)

**Comment by botika** [comment]
The main implementation of SIMD, avx, [loses performance below 11 bytes.](https://github.com/rust-iendo/v_htmlescape/blob/master/benches/src/all.rs#L32-L40)

I propose an operator for expressions, such as the `WS`, to use one or the other depending on whether the operator is or not. Also integrate it so that you can choose different types of escape, latex ...., which could also use SIMD with [this abstraction of the main loop](https://github.com/rust-iendo/v_htmlescape/blob/master/src/avx/loops.rs).

As for the issue #136 , I can write a [static table](https://github.com/rust-iendo/v_htmlescape/blob/master/src/utils.rs#L1-L32) at compile time from askama.toml with the [scalar implementation](https://github.com/rust-iendo/v_htmlescape/blob/master/src/utils.rs#L109-L123). With simd it is more complicated, but it can also be done simply by [calculating the 3 minimum ranges](https://github.com/rust-iendo/v_htmlescape/blob/master/src/avx/mod.rs#L16-L22), later like the previous one.

**Comment by djc** [comment]
I'm sorry -- I don't have the energy right now to dig into this, and I sometimes find it hard to understand what exactly you mean; there's a bit of a language barrier still.

By the implementation of #136/#108 I mean that I think it would be useful to parametrize `Template` and `MarkupDisplay` with a type argument that's bound by an `Escaper` trait which has a single `escape()` method (similar to the current `MarkupDisplay::escape()` method). Instead of just a table of characters to escape in `askama.toml`, we would then configure the name of the `Escaper` impl to use, like this:

```toml
[escape]
html = "v_escape::HtmlEscaper"
```

If nothing is configured, it would default to the `askama_escape::HtmlEscaper`.

**Comment by botika** [comment]
Ok, I only added the specialization.

**Comment by botika** [comment]
I know, damn English, I need linguistic immersion. What I'm trying to say: let's merge the specialization and then we fix this issues.

**Pull request closed without merging**
