### PR TITLE
Add support for warp

### PR DESCRIPTION
**Pull request by aeons**
Add support for Warp's `Reply` trait in template derivations.

### CODE REVIEW

**Comment by djc** [comment]
Hey, sorry for the slowish response to this!

I've been running into trouble from having all these web framework integrations included in my template engine crate (even if optionally). This causes issues because the web framework's dependencies leak into my dep graph, causing problems if conflicting dependencies are used by the web frameworks. So, while I'm open to hosting warp integrations in this repository, I think we'd need a different approach to integrations altogether. See more discussion in #234; my attempts so far have run aground on coherence issues.

Having the integration included in the web framework might be a more attractive solution, but I'm not sure if Sean et al would be open to that (do they already ship some templating integrations?). Alternatively, I need a sustainable way to do the integrations that will let me keep integrations up to date without running into dependency conflicts going forward.

**Comment by aeons** [comment]
That makes sense.

This feels like a place where orphan instances would be nice to have.

There are currently no templating integrations in the warp repo, but I can check if they would be interested.

I can't really tell whether the separate crate approach worked out or not? Is that something I should pursue for this?

**Comment by djc** [comment]
If you want to help figuring out, that would be awesome. Currently I'm thinking that it might be better to have per-integration crates that have their own `Template: askama::Template` traits. Those integration crates could then also contain a blanket implementation that implements `Reply` (or equivalent) for traits that implement these. Then there should be some feature flag in the derive crate (and exposed through the API crate) that makes the code generator implement that extra trait.

**Comment by aeons** [comment]
I haven't updated the documentation, and the mime stuff is just copy/pasted, but this seems to work.

**Comment by djc** [comment]
This is great, thanks! I'd be happy to merge this once you fix up the documentation. Also any generic mime stuff can still live in `askama` if you like, that shouldn't be too big of an issue.

**Comment by djc** [comment]
Also, if possible, it would be nice to have the tests in the askama_warp crate.

**Comment by aeons** [comment]
Alright, I'll make the get_mime_type a `pub fn` then.
Looking at tests now.

**Comment by aeons** [comment]
Right now `cargo test` works in both `askama_warp` and `testing`, but when I run `cargo test` in the workspace, it enables the `warp` feature in `askama_derive` when running the tests in `testing`, which makes the compilation fail.

I can't figure out how to not enable that feature when running the workspace tests.

**Comment by aeons** [comment]
Helpfully, I found this issue https://github.com/rust-lang/cargo/issues/6195
:laughing:

**Comment by djc** [comment]
Recognizing that this *should* never come up in the wild, maybe there's a hack that could work where we add a non-additive feature to `askama_derive` that negates the warp integration. The testing crate would then depend on that feature. How do you feel about that?

**Comment by aeons** [comment]
Something like this?
```rust
if cfg!(feature = "warp") && !cfg!(feature = "test") {
  self.impl_warp_reply(&mut buf);
}
```

**Comment by djc** [comment]
Yes, something like this. I'd like to name the feature `no-integrations` though, in anticipation of using it for the other integrations in the same way.

**Comment by aeons** [comment]
That fixes `testing`, but now `askama_warp` fails since `warp::reply::Reply` is not implemented. I think it relates to the same problem you had in the linked issue.

**Comment by djc** [comment]
Have been thinking about this some more. What if we change the workspace's `default-members` to exclude `askama_warp` (and, in the future, other integration crates)? Can we then run `cargo t --workspace` and `cargo t -p askama_warp` successfully in separate invocations?

**Comment by aeons** [comment]
That seems to work, if you just do `cargo test` in the repo root.
`cargo test --workspace` fails with the same errors though.

**Comment by aeons** [comment]
I removed the `--workspace` from both build and test commands.

From `cargo help build`:
> All packages in the workspace are built if the `--workspace` flag is supplied. The
`--workspace` flag is automatically assumed for a virtual manifest.
Note that `--exclude` has to be specified in conjunction with the `--workspace` flag.

It looks like `--workspace` makes it ignore the `default-members`.

**Comment by djc** [comment]
So I've redone all the other integrations as separate crates now. This has caused some churn, but hopefully rebasing your work should be straightforward -- and it provides a clear model on how to add more integrations. Thanks for working on this with me!

**Comment by djc** [comment]
(Also, please squash all your commits on this branch.)

**Comment by aeons** [comment]
This ended out nicely I think. Thanks.

**Comment by aeons** [comment]
The readme still needs to be updated I guess.

**Comment by djc** [comment]
Thanks! I'll make sure to update the documentation before the next release. Are you comfortable with using the wrap integration from git, or would you prefer to have a release soonish?

**Comment by aeons** [comment]
No rush, I'm just playing around with it for now.

**Pull request merged**
