### PR TITLE
Rust 1.50

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Review by vallentin — DISMISSED** [review]

**Comment by vallentin** [comment]
I'm clearly not awake.

**Review by vallentin — APPROVED** [review]

**Comment by zakcutner** [comment]
Hello! I'm really enjoying using this library, is there any chance this release could be published to crates.io? I'm looking to use #401 in a project and this would really help.

**Comment by vallentin** [comment]
@zakcutner Hey, we just started discussing this #451. There's a few minor things that needs to be ironed out, and then I think we'll do a new release. :)

**Comment by zakcutner** [comment]
Sorry, I hadn't seen this but thanks for getting back to me so fast 😄

**Comment by vallentin** [comment]
No problem, we just started planning this anyways :)

If you _need_ #401 now, then you can always use the repo as a dependency for now:

```toml
[dependencies]
askama = { git = "https://github.com/djc/askama", rev = "2dbdcdf" }
```

**Pull request merged**
