### PR TITLE
Cache generated code

### PR DESCRIPTION
**Pull request by Kijewski**
* Speeds up compilation of a project a lot, when only one, a few, or no templates were changed.
* Speeds up compilation a little even for an initial compilation.
* Far better error messages in generated code.
* The generated code is easily debuggable.

### CODE REVIEW

**Comment by Kijewski** [comment]
I'll tidy up the PR after y'all tell me what you think, e.g. introducing the use of IndexMap, and deriving Hash in their own commits.

**Comment by Kijewski** [comment]
I could suppress the newly generated clippy warnings, too, but actually clippy is quite right with its warnings. Same condition in multiple elif-blocks, calculation X / X, etc. are 99% programming errors (outside of tests).

**Comment by Kijewski** [comment]
I could suppress the newly generated clippy warnings, too, but actually clippy is quite right with its warnings. Same condition in multiple elif-blocks, calculation X / X, etc. are 99% programming errors (outside of tests).

**Comment by djc** [comment]
Do you have benchmark numbers? In a bunch of other projects, I've adopted a different approach that I think might be better: generate code in an integration test. Here's one example, I've done a few others if you're interested:

https://github.com/mattsse/chromiumoxide/pull/80

So the idea would be that we have an askama_build crate that contains the generator and other stuff, which offers a builder API that lets you pass a string like `crate::foo::Bar` with a `Path` to the template for that type, and this would generate the `Template` implementations into a file (formatted with rustfmt) written into the `src` dir as part of an integration test. This is nice because:

* No build script, build scripts slow down compilation pipelines and are a supply chain hazard
* No recompilation of the templates unless needed, no procedural macro expansion except at test time
* Integration test run in CI makes sure that the generated code is never out of date

**Pull request closed without merging**
