### PR TITLE
Bump version numbers in anticipation of beta release

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by djc** [comment]
@vallentin ping?

**Comment by vallentin** [comment]
Once again, I didn't get a notification, and I check each of them daily, it's weird :/

**Review by vallentin — APPROVED** [review]

**Comment by djc** [comment]
I'll start tagging you for review explicitly, maybe that helps? Are you using GH notifications directly or through email? What's your watch status for this repo?

**Comment by vallentin** [comment]
Yeah, maybe tagging will work. Watching is set to "All Activity", and I check the notifications here on GitHub, and not on mail.

I wonder if it has anything to do with you, the owner of the repo making the PR, mixed with not tagging? No clue, just a random thought :)

**Comment by djc** [comment]
I'm pretty sure "all activity" should include new PRs whoever the author, so it seems really weird. Maybe try pinging GH support? They're usually helpful.

**Comment by vallentin** [comment]
Yeah, I'll try that. I got a notification (and mail) that you merged, since I reviewed. However, I just went back and checked (even searched my mail) and this PR is no where to be found. Really odd.

**Pull request merged**
