### PR TITLE
Emit an error if a syntax config already exists

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/djc/askama/issues/674.

I realized that warnings were easy to ignore so I decided to turn it into an error. What do you think?

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
The checks I'm running are far from enough. I'll update it.

**Comment by djc** [comment]
Out of curiosity, is the custom syntax you're working with intended for rustdoc or some other project? What's the use case?

**Comment by GuillaumeGomez** [comment]
No, it's just that I don't like having settings being silently ignored. That's pretty much it. ^^'

**Comment by GuillaumeGomez** [comment]
It should be ready now.

**Comment by djc** [comment]
So can you explain again what problem this is trying to solve? This seems like a bunch of complicated code trying to improve diagnostics for what's like an edge case of an edge case -- in other words, extremely niche...

**Comment by GuillaumeGomez** [comment]
When your config adds a syntax which already exists. A problem I actually encountered in a test of this crate. :laughing:

**Comment by djc** [comment]
Okay, I'm inclined not to take this.

**Comment by GuillaumeGomez** [comment]
Understandeable!

**Pull request closed without merging**
