### PR TITLE
Add section to README for IDE plugins

### PR DESCRIPTION
**Pull request by SamJakob**

### CODE REVIEW

**Review by vallentin — CHANGES_REQUESTED** [review]
Casing mismatch :)

That being said, I'll let djc decide whether this should be added to the readme

**Comment by SamJakob** [comment]
> Casing mismatch :)
> 
> That being said, I'll let djc decide whether this should be added to the readme

Oops, fixed - thanks!

**Comment by djc** [comment]
I don't think I want a badge for it, but I think it would be good to add a bullet in Features list that says something like:

* IDE support available in [JetBrains products](https://plugins.jetbrains.com/plugin/16591-askama-template-support)

**Comment by SamJakob** [comment]
> I don't think I want a badge for it, but I think it would be good to add a bullet in Features list that says something like:
> 
> * IDE support available in [JetBrains products](https://plugins.jetbrains.com/plugin/16591-askama-template-support)
> 
> (Somewhere near the bottom of the list.)

Okay will take out the badge.
I added an IDE support section further down, do you want me to change that?

**Comment by djc** [comment]
> I added an IDE support section further down, do you want me to change that?

Yes, please change it to what I proposed. For now, a whole section for just the single link seems overkill to me.

**Comment by SamJakob** [comment]
> > I added an IDE support section further down, do you want me to change that?
> 
> 
> 
> Yes, please change it to what I proposed. For now, a whole section for just the single link seems overkill to me.

Sure!

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
Thanks!

**Pull request merged**
