### PR TITLE
Create versioned documentation

### PR DESCRIPTION
**Pull request by natemcmaster**
Addresses #720 

This creates a versioned documentation site. I've deployed this in my fork for example:

* Stable docs: https://natemcmaster.github.io/askama/ (notice how this redirects to 0.11.x)
* Unstable docs: https://natemcmaster.github.io/askama/next/index.html
* Outdated releases: https://natemcmaster.github.io/askama/0.10.x/index.html

**Where did docs in 0.10.x/ and 0.11.x/ come from?**

I checked out these folders of documentation from the book/ folder at https://github.com/djc/askama/releases/tag/0.11.0 and https://github.com/djc/askama/releases/tag/0.10.0

### CODE REVIEW

**Comment by djc** [comment]
Thanks for doing the work on this. It seems relatively ugly to have multiple copies of the documentation checked out -- and I'm also not a big fan of having a bunch of shell script orchestrating this. Relative to the required complexity, I feel like I'm okay with the current solution of only having mainline docs? Askama evolves fairly slowly anyway...

**Comment by Kijewski** [comment]
I wonder if we could convert the book to a crate like https://docs.rs/dtolnay/0.0.11/dtolnay/ … So it would be versioned, could be easily linked to, would have the same look and feel as other crates, etc.

**Comment by natemcmaster** [comment]
I didn’t spend much time in this, so no worries about closing and going another direction. 

Some alternatives to explore:

- just have one version of docs, but put annotations inline about features and when they were added. Downside: this can be cumbersome to maintain and easy to misinterpret. 
- bundle all docs into the crates
- Use git to checkout tags instead of putting copies side by side in the main branch
- just maintain a “stable” and “nightly” version of docs 
- release updates frequently so there isn’t a big gap between features and docs.

**Comment by djc** [comment]
I prefer the user experience of mdbooks over manual/user guide documentation on docs.rs. Checking out tags would make it a little bit better, I guess? I definitely don't care about docs for older versions than stable -- but still feels like a lot of indirection when Askama evolves only slowly -- and the documented interface even more slowly.

**Pull request closed without merging**
