### PR TITLE
Add changing delimiters support

### PR DESCRIPTION
**Pull request by botika**
#121

### CODE REVIEW

**Comment by djc** [comment]
Wow, that's fast! Again, thanks for working on this!

I initially suggested changes should be made in the configuration file. Instead, you've built it using attributes. I'm going to guess you did it this way because with my proposal it would be impossible to use different syntax in different test cases within the testing crate.

I think there are two ways to solve this issue:

- Only test different syntaxes at the parser level (using unit tests), instead of end-to-end tests. I think this is a fine way to solve it, though it provides less flexibility to end users.
- Use the configuration file to define named syntaxes and define a default syntax for the crate, while introducing an attribute for a different syntax on a per-template basis. This is a somewhat more involved change, but would be nicely flexible for end users.

Finally, I would like to request that you try to isolate refactoring changes to existing code (or, in fact, any change that's unrelated to the changing the delimiters) into separate commits. So ideally I'd like to have fixing the space in `Node::Call` in a separate commit, moving parts of the parser into an impl in a different commit, and so on. This will make it more explicit what you are refactoring to make this change and it can be a bit more work, but it makes reviewing much easier, increasing chances that we'll be able to find any issues that come up. Let me know if all this makes sense?

**Comment by botika** [comment]
It's a deep refactoring in parser, but basically the functions, `expr_node, cond_block, block_id, match_else_block, when_block, block_match, block_for, block_block, block_macro, block_node, block_comment, parse_template, take_content and parser` to method of the new struct, Parser. 

If those changes have crept in, with the IDE code refactor, I'm sorry. I have fix it. 

It is prepared so that in the `extract` function, previously `TemplateInput::new`, it can pick up configuration from any side. I will implement the second option, but you will detail it with an example of the configuration, which I did not see clearly.

**Comment by botika** [comment]
Now it can be configured by file and by derive with priority in the derive. The configuration file is given the properties `block_start, block_end, expr_start, expr_end, comment_start, comment_end` of 2 characters and the developer has to take care of the combinations of the different "start" braces because the method `take_content`.

**Comment by botika** [comment]
With this last change, is it similar to the idea you had?

**Comment by djc** [comment]
I still want there to be only named syntax (that is, no direct syntax manipulation via attribute fields -- only changing the syntax via an attribute field). I also still want the commit that modifies the parser macros to be split into two parts, one of which is a no-functional change refactoring.

**Comment by botika** [comment]
Now you can create named syntax in `askama.toml`, and add his name to the `default_syntax` attribute without any modifier attribute (`block_start`,..). Modifiers by attribute in addition to this. Ok, now I divide the first commit in two,

**Comment by botika** [comment]
Sorry

**Comment by botika** [comment]
I can remove the modifier attributes but I would like you to explain where the problem is if it is only for test. You already had the cut, if you need anything else let me know.

**Comment by djc** [comment]
So you mentioned having more freedom for the user. I understand how that might be attractive, but as a library maintainer, more freedom for the user means less freedom for me in how to evolve the API. As such, I'd rather be more conservating about exposing API to users, such that maintaining it will be simpler over time.

Additionally, I think Askama is already at the limit of how much attribute fields should be used. It's not great syntax (for example, there's less syntax highlighting at least in my editor) and having long attribute lines doesn't seem very idiomatic. So for this use case of custom syntaxes, which is arguably a bit niche, it seems more than good enough to only allow it to be done in configuration anyway. That has the added benefit to some extent of requiring users to name their syntax, which will make it more obvious what's going on if different syntaxes are used within a single crate.

As for your changes, the commit introducing `Parser` now changes in the `TemplateInput` type to support parser creation, but with this direction, that should likely be rolled back, with `syntax` just becoming a field on `TemplateInput`. 

Could `Parser::parse()` take a reference instead of an owned `self`? Cloning the `Parser` all over the places seems a little ugly.

Can syntaxes be named using `[[syntax.foo]]` rather than having an option `name` inside the syntax block? I think something like that is probably possible with TOML, but I haven't looked deeply into it. I'd prefer not to have a separate `default_syntax` on `Config`, it can just be named entry "default" in the `syntaxes` map. It also seems like we shouldn't need a `Syntax`, an `OptionSyntax` and a `RawSyntax`, although I can see how we might need two rather than three.

Again, thanks for doing this work, I know I'm a bit particular with how I want this to be done -- but as a maintainer, I'm going to be stuck with it for the foreseeable future. If you get tired of it, I can also finish it off myself (though it might take a bit more time). So thanks for working through this with me!

**Comment by botika** [comment]
Ok, I remove the attributes of more, thanks for explaining it to me. 

Due to the lifetimes of the `TemplateInput` properties, it is not possible to copy or clone, since it lives in the heap and the stack at the same time. So it can not be used as an argument of `Parser::parse()`

I do not like clones either, but I have not found a way to call `named_args!` inside the macro `alt!`, `many0!`, etc and even if I did it I would have to clone or copy the `Syntax` struct. Clone could be avoided by a copy if I change the lifetimes, but now they came in the heap from [here](https://github.com/djc/askama/blob/master/askama_derive/src/input.rs#L59). And the main problem with the current implementation of the attributes is that they do not allow to set the lifetime in the stack.
And I was also thinking that we could pair other languages apart from Jinja, with few changes from this struct.

And as for `[[syntax.name]]`, it can be done, but it's a big change in `Config::from_str`, looking for these options by discard in the `Table`, `BTreeMap <String, Value>`. I add the [test with the feature](https://github.com/alexcrichton/toml-rs/blob/master/test-suite/tests/parser.rs#L122).

The three syntaxes were to be able to compose several Syntaxes in another using the overwrite method, if the feature is removed, it remains at 2.

So the main problem that I identify is the lifetime of `TemplateInput` and is a deep refactor. I can put it after these commits, I was already thinking how.

For what I have thought, redo the last commit by removing attributes and removing the 3 Syntax. And another solving the lifetime of `TemplateInput` and all those ugly clones. 
How about?

Thank you very much for your patience, I am learning a lot with Askama.

**Comment by djc** [comment]
The `TemplateInput` should live long enough, though, to just pass it as a reference to everything else? Also ideally you don't pass the full `TemplateInput` to the parser, but instead pass (a reference to) the relevant `Syntax` instance from the `Config` keyed with the attribute field's syntax key (which should also live plenty long enough). Does that make sense?

If doing the other thing with TOML is hard, let's keep that for a follow-up PR to get this all straightened out first.

**Comment by botika** [comment]
The methods for Parser seem good to you? Or try the static function? I do not find another way and I see it correct as long as it is not cloned.

You can use the same lifetime of the [`build_template` function](https://github.com/djc/askama/blob/master/askama_derive/src/lib.rs#L36) for everything else, including `TemplateInput`. In other words, nothing apart from the return of `build_template` must continue to exist. It can be done, but the refactor is deep, I do it?

**Comment by djc** [comment]
Oh, I'd missed that you're passing `mut self` to the `Parser` methods. Is that why you're cloning it around? I think in this case you should be able to just use `&self`. If you do that, I don't see why you'd need deep refactoring. What I want is kind of like this:

- Restore `TemplateInput::new()`, `TemplateInput` will include a new `syntax: Option<&str>` field
- `build_template()` gets a `&Syntax` out of the `Config::syntaxes` map based on `input.syntax`
- `Parser::new()` takes a `&Syntax`
- `Parser` methods take `&self`
- `generator::generate()` also takes a `&Syntax`

Do you think that could work?

**Comment by botika** [comment]
Ok I like it. 

I will have to dismantle the Config a little to do this, it would be `Config::new(& str)`, remove `Config::from_str` and the logic of the `fs: read_to_string` will draw it to `TemplateInput: new`. So the `config` disappears from `TemplateInput` in favor of `dirs: Vec<PathBuf>` and `Parser`. 

The only difference is to change in `TemplateInput`, `config` for `dirs` and let that config die. The idea is to eliminate  the config that we do not need and deserialize without alloc. How about?

**Comment by djc** [comment]
I don't understand why you want to kill `Config` or why you'd have to. I do think `TemplateInput::new()` instantiating the `Config` is a little bit off, and it would be better to move that into `build_template()`, which would then pass `&Config` into `TemplateInput::new()`?

**Comment by botika** [comment]
You can not put the `"&"` in the `self` field of the macro `method!`. The only way to use `call_m!` more than once in the same method is to use `mut self` https://docs.rs/nom/4.0.0/nom/methods/index.html. 
Now I'll do the refactor for` TemplateInput::new(ast, config)`.

**Comment by botika** [comment]
TemplateInput can not borrow Parser since it is yours since it created it in yours constructor. 

Tomorrow I will continue with the few commits that are missing.

**Comment by botika** [comment]
I do not know if well understood. 

The alternative to the `methods!` of Nom are the `named_args!`. I tested and can not pass arguments, I have looked at all the implementations with Nom that I have found and none use any of the 2. 

So I do not see how to pass the Syntax as an argument of `parser::parse()` and get it to `block_match` for example.

In the last refactor I have separated the logic of reading the configuration file of the Config contructor, because the string can only live above Config, if not it gives me the typical error of lifetime, "borrowed...". 

how about? 
I have looked at all the repositories that use Nom and none do this. If you have a small example of how to do it with the `named_args!`, I have run out of options in this topic.

**Comment by botika** [comment]
It is already totally static.

**Comment by djc** [comment]
Ohh, this is looking great! Using `named_args!()` for the parser seems like a very nice solution. I'm going to merge this now and tweak some things just a little bit.

**Pull request merged**
