### PR TITLE
Fix cyclic dependency

### LINKED ISSUE #1004: Template compilation infinite loop / failed cycle detection
Hello,

I ran into the same bug as is reported is issue #515. That issue was closed as solved in 2021, with some cycle detection added in, but I have a simple case the cycle detection fails to trigger on.

The following project will reproduce it, running cargo build never halts.

`src/lib.rs`:
```rust
use askama::Template;

#[derive(Template)]
#[template(path = "page.html")]
pub struct Page;
```

`templates/base.html`:
```
{% extends base.html %}
```
`templates/page.html`:
```
{% extends base.html %}
```

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #1004.

We forgot to check a corner-case apparently.

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by and-reas-se** [comment]
I looked at the PR noticed that both tests appear to test the same thing. Did you mean to have one of the test templates extend the other?

**Comment by GuillaumeGomez** [comment]
They don't test the same things. One is the case that was already handled ("cyclic1.html" extending itself) and the other checks the case your discovered ("cyclic2.html" extending "cyclic1.html").

**Comment by and-reas-se** [comment]
In the PR that does not appear to be the case, cycle1.html extends cycle1.html, and cycle2.html extends cycle2.html.

**Comment by GuillaumeGomez** [comment]
... I'm ashamed. Thanks for the catch! Want to send a PR to update `cyclic2.html`?

**Comment by and-reas-se** [comment]
Sure, I can do that.

**Comment by GuillaumeGomez** [comment]
Awesome! To update UI test, you can do: `TRYBUILD=overwrite cargo test`.

**Pull request merged**
