### PR TITLE
Add not to borrow tag

### PR DESCRIPTION
**Pull request by botika**
#107

### CODE REVIEW

**Comment by djc** [comment]
I'm afraid I don't like this solution very much. If you want to make progress on #107, I think we need some analysis on exactly what the current generated code can handle and where it fails, and what avenues are available to make the latter cases more ergonomic. Adding an unfamiliar sigil to magically fix this problem seems like a hard-to-learn and hard-to-understand solution to the problem.

**Comment by botika** [comment]
I have tried to explain it in the documentation a little better, it is not much better :sweat_smile: . It is for cases in which as in the return of the `clone()` that returns the element with the borrow. In other words, you have to launch a function that returns `&` needs it. Suggestions for documentation are accepted. Without tag I do not know how we can know when the function returns a borrow. What do you think?

**Comment by djc** [comment]
Still don't like it, sorry. 😞 Maybe we should just document the constraints here rather than adding the new operator, with a workaround.

**Comment by botika** [comment]
If much better document and give alternatives to these. Ok, I close

**Pull request closed without merging**
