### PR TITLE
Add length & count filters

### PR DESCRIPTION
**Pull request by defyrlt**
cc https://github.com/djc/askama/issues/18

### CODE REVIEW

**Comment by djc** [comment]
Hey, thanks for the PR! Do you actually use these in your templates? If so, do you use them primarily for string lengths? I'm not sure the conversion through `Display` makes sense for these filters, it seems somewhat wasteful especially if you're going to pass strings to them anyway.

**Comment by defyrlt** [comment]
Yea, personally I use it for strings, can't remember last time I needed filter like that for a non-string. I'll change it to work with `String` instead (or `&str` if possible)

**Comment by djc** [comment]
Maybe try with `AsRef<&str>`, that should cover all the cases?

**Comment by djc** [comment]
And in that case, what about just using `.len()` instead of a filter?

**Comment by defyrlt** [comment]
What if there's a filter that is producing a different string? You can't do something like `(foo|bar).len()`, can you?

**Comment by djc** [comment]
I think that should work, have you tried it?

**Comment by defyrlt** [comment]
Actually, it does work! I'll close this then.

**Comment by defyrlt** [comment]
p.s: a good thing to document!

**Comment by djc** [comment]
Got any suggestions for where/how to document? For me it's fairly obvious that this should work, but obviously I'm way too familiar with the internals.

**Pull request closed without merging**
