### PR TITLE
Upgrade nom to 6.2.1 (bitvec & funty issue)

### PR DESCRIPTION
**Pull request by leehambley**
More information here https://github.com/djc/askama/issues/522.

I haven't checked the contributing guidelines here if contributors are expected to also send changes to versions, changelogs, etc - but I will follow-up in this PR over the next hours/days.

### CODE REVIEW

**Comment by djc** [comment]
I don't quite want to pull in the alpha. Let's stick to 6.2.1 if that fixes things.

**Comment by leehambley** [comment]
6.2.1 would allow you to pin `nom`, rather than `funty`, however it cannot coexist with the MySQL crate which forces funty at 1.2.0.

Unfortunately, it seems I need the alpha specifically, although askama might benefit from the (slightly) improved Cargo.toml iny first commit Herr.

**Comment by djc** [comment]
I don't really want to depend on an alpha there, given the [issues](https://internals.rust-lang.org/t/changing-cargo-semver-compatibility-for-pre-releases/14820) with depending on pre-release versions. I've tried to [lobby](https://github.com/Geal/nom/issues/1323#issuecomment-890843025) upstream nom a bit more.

I'd be happy to take your first commit though.

**Comment by leehambley** [comment]
I suspect it's easier for you to simply cherry-pick it, or I'm happy to close this PR and send one for just the first commit. 

Just let me know what you prefer :+1:

**Comment by djc** [comment]
If you just `git reset --hard HEAD^ && git push -f`, that should take care of things.

**Comment by leehambley** [comment]
Done, once I see that you are merged here, I'll go back to my `af7b1ab ` version where I have the alpha, so I can use my fork until this upstream nonsesne resolves itself. Thanks @djc

**Review by djc — APPROVED** [review]

**Pull request merged**
