### PR TITLE
Integration spring cleaning

### PR DESCRIPTION
**Pull request by djc**
Recent crates.io downloads:

* askama_axum: 30k
* askama_actix: 4k
* askama_rocket: 1130
* askama_tide: 978
* askama_warp: 882
* askama_gotham: 366
* askama_hyper: 143
* askama_mendes: 0 (never published)

The overhead of maintaining these integrations isn't very large, but it's also not zero. I think it makes sense to clean some of these out.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]
Less code to maintain is always better. :)

**Comment by djc** [comment]
Partially triggered by unmaintained crate advisory which cargo-deny is newly defaulting to erroring on:

```
error[unmaintained]: `aes-soft` has been merged into the `aes` crate
   ┌─ /github/workspace/Cargo.lock:18:1
   │
18 │ aes-soft 0.6.4 registry+https://github.com/rust-lang/crates.io-index
   │ -------------------------------------------------------------------- unmaintained advisory detected
   │
   = ID: RUSTSEC-2021-0060
   = Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0060
   = Please use the `aes` crate going forward. The new repository location is at:
     
     <https://github.com/RustCrypto/block-ciphers/tree/master/aes>
     
     AES-NI is now autodetected at runtime on `i686`/`x86-64` platforms.
     If AES-NI is not present, the `aes` crate will fallback to a constant-time
     portable software implementation.
     
     To force the use of a constant-time portable implementation on these platforms,
     even if AES-NI is available, use the new `force-soft` feature of the `aes`
     crate to disable autodetection.
   = Announcement: https://github.com/RustCrypto/block-ciphers/pull/200
   = Solution: No safe upgrade is available!
   = aes-soft v0.6.4
     └── aes v0.6.0
         └── aes-gcm v0.8.0
             └── cookie v0.14.4
                 └── http-types v2.12.0
                     ├── async-sse v4.1.0
                     │   └── tide v0.16.0
                     │       └── askama_tide v0.16.0
                     ├── http-client v6.5.3
                     │   └── tide v0.16.0 (*)
                     └── tide v0.16.0 (*)

error[unmaintained]: `aesni` has been merged into the `aes` crate
   ┌─ /github/workspace/Cargo.lock:19:1
   │
19 │ aesni 0.10.0 registry+https://github.com/rust-lang/crates.io-index
   │ ------------------------------------------------------------------ unmaintained advisory detected
   │
   = ID: RUSTSEC-2021-0059
   = Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0059
   = Please use the `aes` crate going forward. The new repository location is at:
     
     <https://github.com/RustCrypto/block-ciphers/tree/master/aes>
     
     AES-NI is now autodetected at runtime on `i686`/`x86-64` platforms.
     If AES-NI is not present, the `aes` crate will fallback to a constant-time
     portable software implementation.
     
     To prevent this fallback (and have absence of AES-NI result in an illegal
     instruction crash instead), continue to pass the same RUSTFLAGS which were
     previously required for the `aesni` crate to compile:
     
     ```
     RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
     ```
   = Announcement: https://github.com/RustCrypto/block-ciphers/pull/200
   = Solution: No safe upgrade is available!
   = aesni v0.10.0
     └── aes v0.6.0
         └── aes-gcm v0.8.0
             └── cookie v0.14.4
                 └── http-types v2.12.0
                     ├── async-sse v4.1.0
                     │   └── tide v0.16.0
                     │       └── askama_tide v0.16.0
                     ├── http-client v6.5.3
                     │   └── tide v0.16.0 (*)
                     └── tide v0.16.0 (*)

error[unmaintained]: `cpuid-bool` has been renamed to `cpufeatures`
   ┌─ /github/workspace/Cargo.lock:98:1
   │
98 │ cpuid-bool 0.2.0 registry+https://github.com/rust-lang/crates.io-index
   │ ---------------------------------------------------------------------- unmaintained advisory detected
   │
   = ID: RUSTSEC-2021-0064
   = Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0064
   = Please use the `cpufeatures`` crate going forward:
     
     <https://github.com/RustCrypto/utils/tree/master/cpufeatures>
     
     There will be no further releases of `cpuid-bool`.
   = Announcement: https://github.com/RustCrypto/utils/pull/381
   = Solution: No safe upgrade is available!
   = cpuid-bool v0.2.0
     └── polyval v0.4.5
         └── ghash v0.3.1
             └── aes-gcm v0.8.0
                 └── cookie v0.14.4
                     └── http-types v2.12.0
                         ├── async-sse v4.1.0
                         │   └── tide v0.16.0
                         │       └── askama_tide v0.16.0
                         ├── http-client v6.5.3
                         │   └── tide v0.16.0 (*)
                         └── tide v0.16.0 (*)

error[unmaintained]: stdweb is unmaintained
    ┌─ /github/workspace/Cargo.lock:313:1
    │
313 │ stdweb 0.4.20 registry+https://github.com/rust-lang/crates.io-index
    │ ------------------------------------------------------------------- unmaintained advisory detected
    │
    = ID: RUSTSEC-2020-0056
    = Advisory: https://rustsec.org/advisories/RUSTSEC-2020-0056
    = The author of the `stdweb` crate is unresponsive.
      
      Maintained alternatives:
      
      - [`wasm-bindgen`](https://github.com/rustwasm/wasm-bindgen)
      - [`js-sys`](https://github.com/rustwasm/wasm-bindgen/tree/master/crates/js-sys)
      - [`web-sys`](https://github.com/rustwasm/wasm-bindgen/tree/master/crates/web-sys)
    = Announcement: https://github.com/koute/stdweb/issues/403
    = Solution: No safe upgrade is available!
    = stdweb v0.4.20
      └── time v0.2.27
          ├── cookie v0.14.4
          │   └── http-types v2.12.0
          │       ├── async-sse v4.1.0
          │       │   └── tide v0.16.0
          │       │       └── askama_tide v0.16.0
          │       ├── http-client v6.5.3
          │       │   └── tide v0.16.0 (*)
          │       └── tide v0.16.0 (*)
          └── cookie v0.15.2
              └── gotham v0.7.2
                  └── askama_gotham v0.15.0
```

@jbr are you going to update tide to deal with these soon?

**Comment by Kijewski** [comment]
> I think it makes sense to clean some of these out.

Yes, I think that's reasonable.

**Comment by jbr** [comment]
> @jbr are you going to update tide to deal with these soon?

I'm not sure what to do here but ccing @yoshuawuyts and @fishrock123 — I personally think tide should be archived since nobody is maintaining it, but I'm not the right point of contact for tide decisions. Yosh committed to doing maintenance releases in https://github.com/http-rs/tide/discussions/888#discussioncomment-2669714 but there hasn't been a release in several years, and I'm not sure what the path forward is.

To the extent that I have responsibility for the code that I wrote in askama, I'd be fully content just removing it from askama. Let me know if you'd like me to PR that.

**Comment by djc** [comment]
Thanks for the feedback -- I've submitted #975 to remove askama_tide.

**Pull request merged**
