### PR TITLE
Fix `clippy::derive_partial_eq_without_eq` warning

### PR DESCRIPTION
**Pull request by Kijewski**

### CODE REVIEW

**Comment by djc** [comment]
Thanks; I should have mentioned that I filed a clippy issue for this:

https://github.com/rust-lang/rust-clippy/issues/8875

**Comment by Kijewski** [comment]
Yea, that should be fixed upstream. Interestingly enough only in askama_rocket the bug shows.

**Comment by djc** [comment]
Because Rocket runs against nightly.

**Comment by djc** [comment]
I guess with Rocket 0.5 rcs we actually don't need nightly anymore?

**Pull request closed without merging**
