### PR TITLE
askama_gotham: upgrade to gotham 0.7

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by djc** [comment]
(Let's ignore the unrelated Actix failure, which I mentioned in #553.)

**Review by vallentin — DISMISSED** [review]

**Comment by vallentin** [comment]
Wait, the CI failed.

**Comment by djc** [comment]
@vallentin which I mentioned in my earlier comment. :)

**Review by vallentin — APPROVED** [review]
I can't read I guess :)

**Pull request merged**
