### PR TITLE
Allow whitespace trimming in {{raw}} blocks 

### PR DESCRIPTION
**Pull request by Kijewski**
This PR is based on #545 and #541.

### CODE REVIEW

**Review by djc — APPROVED** [review]
LGTM. After rebasing this on top of main, feel free to merge it!

**Comment by Kijewski** [comment]
Huh, do you know why the CI isn't checking the PR?

**Comment by djc** [comment]
Probably just a glitch, try pushing it again?

**Comment by Kijewski** [comment]
The main branch is protected, so I cannot push directly to it without an approval, and I cannot self-approve my PR. So, you or @vallentin need to approve the PR. :)

**Review by vallentin — APPROVED** [review]
@djc said it was all good, so just approving so you can merge :)

**Pull request merged**
